### ISSUE TITLE
Code for Darcy Flow does not work

### ISSUE THREAD

**Issue by Shancong-Mou** [neuraloperator/PINO#12]
Hi, 

Amazing project! I am able to duplicate the Burgers experiment. However, the code for Darcy Flow does not work. 

python3 train_operator.py --config_path configs/pretrain/Darcy-pretrain.yaml

with the following error:
Traceback (most recent call last):
  File "train_operator.py", line 133, in <module>
    train_2d(args, config)
  File "train_operator.py", line 90, in train_2d
    num=data_config['n_samples'], 
KeyError: 'n_samples'

**Comment by alabaykazakh** [comment]
> Hi,
> 
> Amazing project! I am able to duplicate the Burgers experiment. However, the code for Darcy Flow does not work.
> 
> python3 train_operator.py --config_path configs/pretrain/Darcy-pretrain.yaml
> 
> with the following error: Traceback (most recent call last): File "train_operator.py", line 133, in train_2d(args, config) File "train_operator.py", line 90, in train_2d num=data_config['n_samples'], KeyError: 'n_samples'

write `n_samples` instead of `n_sample` in configs/pretrain/Darcy-pretrain.yaml file.

**Comment by Shancong-Mou** [comment]
> > Hi,
> > Amazing project! I am able to duplicate the Burgers experiment. However, the code for Darcy Flow does not work.
> > python3 train_operator.py --config_path configs/pretrain/Darcy-pretrain.yaml
> > with the following error: Traceback (most recent call last): File "train_operator.py", line 133, in train_2d(args, config) File "train_operator.py", line 90, in train_2d num=data_config['n_samples'], KeyError: 'n_samples'
> 
> write `n_samples` instead of `n_sample` in configs/pretrain/Darcy-pretrain.yaml file.

Thanks for your feedback. I just fix that issue and compiled again, a new error appears:

Traceback (most recent call last):
  File "train_operator.py", line 133, in <module>
    train_2d(args, config)
  File "train_operator.py", line 98, in train_2d
    pad_ratio=config['model']['pad_ratio']).to(device)
KeyError: 'pad_ratio'

I am wondering if the author accidentally push the run version of the code?

**Comment by devzhk** [comment]
Hey, 

Sorry, my bad. I added a new feature to the FNO architecture (padding) and didn't merge it correctly with the main branch. 

I just updated the repo.  For Darcy exp, you can run the following to train the operator
```bash
python3 train_darcy.py --config configs/operator/Darcy-pretrain.yaml
```
To test the trained operator on test set, run 
```bash
python3 train_darcy.py --config configs/operator/Darcy-pretrain.yaml --test --ckpt [path to the checkpoint]
```

Regards

**Comment by KevinJianLin** [comment]
Thanks for putting this together. 

For train_2d_operator() function, what does variable "y" refer to ? I don't see anything in the argument nor in the code. Does it refer to "u"? I got an error by running it saying that "y" is not defined.

 for data_ic, u, pde_ic in train_loader:
            data_ic, u, pde_ic = data_ic.to(rank), u.to(rank), pde_ic.to(rank)

            optimizer.zero_grad()

            # data loss
            if data_weight > 0:
                pred = model(data_ic).squeeze(dim=-1)
                pred = pred * mollifier
                data_loss = myloss(pred, y)
