### ISSUE TITLE
Bugers data link error

### ISSUE THREAD

**Issue by jianqing666** [NeuralOperator/PINO#16]
Dear authors, 
Thank you for your very interesting research. I get an error when I click on the link to burgers_pino.mat, can you update this link?

**Comment by qsun1** [comment]
[burgers_pino.mat](https://hkzdata.s3.us-west-2.amazonaws.com/PINO/burgers_pino.mat)

**Comment by qsun1** [comment]
https://drive.google.com/drive/folders/1do_kCc5rNcPtSjeuQ_GF3BlEG-Zvtp86?usp=sharing
